language: node_js
node_js:
  - "0.11.13"

script:
  - ./.travis/after_install.sh
  - ./.travis/package.sh

after_success: ./.travis/after_success.sh


#
# Thanks to @pwmckenna (https://github.com/pwmckenna/todium/blob/master/.travis.yml)
# for the example how files can be pushed to gh-pages branch safely.
#
env:
  global:
    # GH_OAUTH_TOKEN is the oauth token generated as described at
    # https://help.github.com/articles/creating-an-oauth-token-for-command-line-use
    #
    # curl -u 'username' -d '{"scopes":["repo"],"note":"push to gh-pages from travis"}' https://api.github.com/authorizations
    #
    # It must be encrypted using the travis gem
    # http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
    #
    # travis encrypt GH_OAUTH_TOKEN=11223344
    #
    # Copy the resulting "secure" property here:
    - secure: "E7Ox7Yme3FKhDG/38NLJtgLP0UP3GJSPJzV0dI2KdoFyZTNQemZxv1ARPheqYZwZz0Pw0ApH4SRUzrpuIPu8KrOZquMAMB4YdQ3yXXtXNlude4z5ILRle1/J2DYKEnJyfZHHiqpbQwni4ikbEOa8gEUa+py1ASb/5gw854YCi7Q="

    # GH_USER_NAME & GH_PROJECT_NAME
    # The Github Account you created the OAuth token with and the repo you
    # want to push the builds
    - GH_USER_NAME: swissmanu
    - GH_PROJECT_NAME: orchestra-builds

    # GIT_AUTHOR_NAME & GIT_AUTHOR_EMAIL
    # When pushing to the gh-pages branch, these informtion are used to
    # perform the git commit
    - GIT_AUTHOR_NAME: "TravisCI"
    - GIT_AUTHOR_EMAIL: "noreply@travis-ci.org"

    # NW_VERSION
    # The version of nw.js to use for build
    - NW_VERSION: "0.11.6"

    # CI_HOME
    # A shortcut to the directory where travis cloned the actual git repo
    - CI_HOME=`pwd`

    # RESULT_PDF_PATH
    # A shortcut to the built PDF document
    - ORCHESTRA_BUILD=$CI_HOME/build/orchestra
